### ISSUE TITLE
Redis histogram metadata and metric keys not saved

### ISSUE THREAD

**Issue by itongTripleLift** [PromPHP/prometheus_client_php#23] opened 2020-11-06 15:28 UTC
When observing a histogram, there's a chance the metric metadata and keys are not saved set in Redis.

On https://github.com/PromPHP/prometheus_client_php/blob/master/src/Prometheus/Storage/Redis.php#L188-L191, there's a conditional checking the return value of hIncrByFloat with the value passed in. The only time this check can be `true` is the first time the metric is observed. Subsequent calls will always return false since `increment` would always be greater.

Per https://redis.io/commands/incrbyfloat, the precision of the output of hIncrByFloat is fixed at 17. Floats that are being observed with a precision of > 17 (e.g. 0.005) will cause the check to fail.

Since the metadata and metric keys are never saved, the metric never gets rendered.

Code To Reproduce:
```
        $redis = new Redis([
            'host' => 'localhost',
            'port' => 6379,
            'timeout' => 0.1,
            'read_timeout' => 10,
            'persistent_connections' => false,
            'prefix' => 'PROMETHEUS_' . gethostname(),
        ]);
        $collectorRegistry = new CollectorRegistry($redis);
        $renderer = new RenderTextFormat();

        $histogram = $collectorRegistry->getOrRegisterHistogram(
            'bug_report',
            'not_rendered',
            'Bug report for histograms not rendering'
        );

        $histogram->observe(0.01);
        $metrics = $collectorRegistry->getMetricFamilySamples();

        header('Content-Type: ' . RenderTextFormat::MIME_TYPE);
        echo $renderer->render($metrics);
```

**Comment by LKaemmerling** [comment] 2020-11-09 06:27
Hey @itongTripleLift ,

i think i don't get your problem. With my tests locally everything is fine:

observe(0.01):
```
# HELP bug_report_not_rendered Bug report for histograms not rendering
# TYPE bug_report_not_rendered histogram
bug_report_not_rendered_bucket{le="0.005"} 0
bug_report_not_rendered_bucket{le="0.01"} 1
bug_report_not_rendered_bucket{le="0.025"} 1
bug_report_not_rendered_bucket{le="0.05"} 1
bug_report_not_rendered_bucket{le="0.075"} 1
bug_report_not_rendered_bucket{le="0.1"} 1
bug_report_not_rendered_bucket{le="0.25"} 1
bug_report_not_rendered_bucket{le="0.5"} 1
bug_report_not_rendered_bucket{le="0.75"} 1
bug_report_not_rendered_bucket{le="1"} 1
bug_report_not_rendered_bucket{le="2.5"} 1
bug_report_not_rendered_bucket{le="5"} 1
bug_report_not_rendered_bucket{le="7.5"} 1
bug_report_not_rendered_bucket{le="10"} 1
bug_report_not_rendered_bucket{le="+Inf"} 1
bug_report_not_rendered_count 1
bug_report_not_rendered_sum 0.01
# HELP php_info Information about the PHP environment.
# TYPE php_info gauge
php_info{version="7.4.11"} 1
```

(Bucket 0.05 is 0, because 0.01 is > 0.05)

Now when i change the observe to `0.001` (I cleared the redis between both runs)
```
# HELP bug_report_not_rendered Bug report for histograms not rendering
# TYPE bug_report_not_rendered histogram
bug_report_not_rendered_bucket{le="0.005"} 1
bug_report_not_rendered_bucket{le="0.01"} 1
bug_report_not_rendered_bucket{le="0.025"} 1
bug_report_not_rendered_bucket{le="0.05"} 1
bug_report_not_rendered_bucket{le="0.075"} 1
bug_report_not_rendered_bucket{le="0.1"} 1
bug_report_not_rendered_bucket{le="0.25"} 1
bug_report_not_rendered_bucket{le="0.5"} 1
bug_report_not_rendered_bucket{le="0.75"} 1
bug_report_not_rendered_bucket{le="1"} 1
bug_report_not_rendered_bucket{le="2.5"} 1
bug_report_not_rendered_bucket{le="5"} 1
bug_report_not_rendered_bucket{le="7.5"} 1
bug_report_not_rendered_bucket{le="10"} 1
bug_report_not_rendered_bucket{le="+Inf"} 1
bug_report_not_rendered_count 1
bug_report_not_rendered_sum 0.001
# HELP php_info Information about the PHP environment.
# TYPE php_info gauge
php_info{version="7.4.11"} 1
```

and then, a third test case was:
Running first with observe (0.01), and then with observe(0.01):
```
# HELP bug_report_not_rendered Bug report for histograms not rendering
# TYPE bug_report_not_rendered histogram
bug_report_not_rendered_bucket{le="0.005"} 1
bug_report_not_rendered_bucket{le="0.01"} 2
bug_report_not_rendered_bucket{le="0.025"} 2
bug_report_not_rendered_bucket{le="0.05"} 2
bug_report_not_rendered_bucket{le="0.075"} 2
bug_report_not_rendered_bucket{le="0.1"} 2
bug_report_not_rendered_bucket{le="0.25"} 2
bug_report_not_rendered_bucket{le="0.5"} 2
bug_report_not_rendered_bucket{le="0.75"} 2
bug_report_not_rendered_bucket{le="1"} 2
bug_report_not_rendered_bucket{le="2.5"} 2
bug_report_not_rendered_bucket{le="5"} 2
bug_report_not_rendered_bucket{le="7.5"} 2
bug_report_not_rendered_bucket{le="10"} 2
bug_report_not_rendered_bucket{le="+Inf"} 2
bug_report_not_rendered_count 2
bug_report_not_rendered_sum 0.011
# HELP php_info Information about the PHP environment.
# TYPE php_info gauge
php_info{version="7.4.11"} 1
```

So i guess i don't get your problem :) Redis limit the output (just the output) to 17 digits after the dot, so it should work everything. Could you please try to clarify your problem a bit more? (Maybe with sample outputs)?

Thank you!

**Comment by itongTripleLift** [comment] 2020-11-09 14:54
Hey @LKaemmerling thanks for taking a look.

I noticed something interesting with your histogram floats. They don't seem to have the precision that we're seeing, which may explain why it's working for you.

Here's some sample output:

Running observe(0.01)
```
# HELP php_info Information about the PHP environment.
# TYPE php_info gauge
php_info{version="7.4.9"} 1
```

Running observe(1)
```
# HELP bug_report_not_rendered Bug report for histograms not rendering
# TYPE bug_report_not_rendered histogram
bug_report_not_rendered_bucket{le="0.005000000000000000104083408558608425664715468883514404296875"} 0
bug_report_not_rendered_bucket{le="0.01000000000000000020816681711721685132943093776702880859375"} 0
bug_report_not_rendered_bucket{le="0.025000000000000001387778780781445675529539585113525390625"} 0
bug_report_not_rendered_bucket{le="0.05000000000000000277555756156289135105907917022705078125"} 0
bug_report_not_rendered_bucket{le="0.07499999999999999722444243843710864894092082977294921875"} 0
bug_report_not_rendered_bucket{le="0.1000000000000000055511151231257827021181583404541015625"} 0
bug_report_not_rendered_bucket{le="0.25"} 0
bug_report_not_rendered_bucket{le="0.5"} 0
bug_report_not_rendered_bucket{le="0.75"} 0
bug_report_not_rendered_bucket{le="1"} 1
bug_report_not_rendered_bucket{le="2.5"} 1
bug_report_not_rendered_bucket{le="5"} 1
bug_report_not_rendered_bucket{le="7.5"} 1
bug_report_not_rendered_bucket{le="10"} 1
bug_report_not_rendered_bucket{le="+Inf"} 1
bug_report_not_rendered_count 1
bug_report_not_rendered_sum 1
# HELP php_info Information about the PHP environment.
# TYPE php_info gauge
php_info{version="7.4.9"} 1
```

Running observe(1) and then observe(0.01)
```
# HELP bug_report_not_rendered Bug report for histograms not rendering
# TYPE bug_report_not_rendered histogram
bug_report_not_rendered_bucket{le="0.005000000000000000104083408558608425664715468883514404296875"} 0
bug_report_not_rendered_bucket{le="0.01000000000000000020816681711721685132943093776702880859375"} 1
bug_report_not_rendered_bucket{le="0.025000000000000001387778780781445675529539585113525390625"} 1
bug_report_not_rendered_bucket{le="0.05000000000000000277555756156289135105907917022705078125"} 1
bug_report_not_rendered_bucket{le="0.07499999999999999722444243843710864894092082977294921875"} 1
bug_report_not_rendered_bucket{le="0.1000000000000000055511151231257827021181583404541015625"} 1
bug_report_not_rendered_bucket{le="0.25"} 1
bug_report_not_rendered_bucket{le="0.5"} 1
bug_report_not_rendered_bucket{le="0.75"} 1
bug_report_not_rendered_bucket{le="1"} 2
bug_report_not_rendered_bucket{le="2.5"} 2
bug_report_not_rendered_bucket{le="5"} 2
bug_report_not_rendered_bucket{le="7.5"} 2
bug_report_not_rendered_bucket{le="10"} 2
bug_report_not_rendered_bucket{le="+Inf"} 2
bug_report_not_rendered_count 2
bug_report_not_rendered_sum 1.01
# HELP php_info Information about the PHP environment.
# TYPE php_info gauge
php_info{version="7.4.9"} 1
```

Here's some extra output:
var_dump of (0.01)
`float 0.01000000000000000020816681711721685132943093776702880859375`

Returned from the Lua script in. `updateHistogram`. Index 0 is `increment` returned by `hIncrByFloat`. Index 1 is ARGV[3]:
```
/var/www/vendor/promphp/prometheus_client_php/src/Prometheus/Storage/Redis.php:206:
array (size=2)
  0 => string '0.01' (length=4)
  1 => string '0.01000000000000000020816681711721685132943093776702880859375' (length=61)
```

**Comment by LKaemmerling** [comment] 2020-11-09 14:57
Can you tell me a bit more about your test system? Which redis version, which phpredis version? For my tests i used the latest phpredis version.

**Comment by nickpoulos** [comment] 2020-11-09 14:59
Hmm interesting. I was playing with it more over the weekend, and I did observe behavior as I Hou described. 

With a fresh spin up, no metrics initialized, `/metrics` looks like: 

```
# HELP php_info Information about the PHP environment.
# TYPE php_info gauge
php_info{version="7.4.11"} 1
```

If I take the code I Hou provided, and run it with `->observe(.01)` using a floatval as the initial value, I will not see any metrics rendered for the histogram and `/metrics` looks the same as the initial one above.  

From there, If I take the code I Hou provided, and run it with `->observe(1)`, using an integer as the initial value, the histogram metrics will appear, and `/metrics` looks something like: 

```
# HELP bug_report_rendered Bug report for histograms not rendering
# TYPE bug_report_rendered histogram
bug_report_rendered_bucket{le="0.005000000000000000104083408558608425664715468883514404296875"} 0
bug_report_rendered_bucket{le="0.01000000000000000020816681711721685132943093776702880859375"} 0
bug_report_rendered_bucket{le="0.025000000000000001387778780781445675529539585113525390625"} 0
bug_report_rendered_bucket{le="0.05000000000000000277555756156289135105907917022705078125"} 0
bug_report_rendered_bucket{le="0.07499999999999999722444243843710864894092082977294921875"} 0
bug_report_rendered_bucket{le="0.1000000000000000055511151231257827021181583404541015625"} 0
bug_report_rendered_bucket{le="0.25"} 1
bug_report_rendered_bucket{le="0.5"} 1
bug_report_rendered_bucket{le="0.75"} 1
bug_report_rendered_bucket{le="1"} 1
bug_report_rendered_bucket{le="2.5"} 4
bug_report_rendered_bucket{le="5"} 6
bug_report_rendered_bucket{le="7.5"} 6
bug_report_rendered_bucket{le="10"} 6
bug_report_rendered_bucket{le="+Inf"} 8
bug_report_rendered_count 8
bug_report_rendered_sum 1026.00000000000004508
# HELP creative_scan_workers_buffer_result Number of creatives buffered/skipped
# TYPE creative_scan_workers_buffer_result counter
creative_scan_workers_buffer_result{result="buffered"} 2
# HELP php_info Information about the PHP environment.
# TYPE php_info gauge
php_info{version="7.4.11"} 1
```

But if you notice, we are using the default values for buckets, but the precision in our buckets is much larger?

**Comment by nickpoulos** [comment] 2020-11-09 15:35
This testing is being done locally, using redis:alpine latest docker images, so v6.x. 

As for PECL: 

```
[creative-scan] www: $ php --ri redis

redis

Redis Support => enabled
Redis Version => 5.3.1
Redis Sentinel Version => 0.1
Available serializers => php, json
```

**Comment by LKaemmerling** [comment] 2020-11-10 06:33
I tried it now with the `redis:alpine` image (using redis 6.0.9) and I can't reproduce it. Which client version do you use? Could you try to use the master branch? 

Things i tried (just to exclude the possibilities):
- Running redis locally within a docker container
- Running redis locally (on host)
- Running redis remote within a docker container
- Running redis remote (on host)

So i really thing the problem is not bound to redis itself. Can you try to use the InMemory Storage? 

And just for the record:
```
➜ php --ri redis

redis

Redis Support => enabled
Redis Version => 5.3.2
Redis Sentinel Version => 0.1
Available serializers => php, json
```

**Comment by itongTripleLift** [comment] 2020-11-10 16:36
Here's the test result using InMemory Storage:

observe(0.01)
```
# HELP bug_report_not_rendered Bug report for histograms not rendering
# TYPE bug_report_not_rendered histogram
bug_report_not_rendered_bucket{le="0.005000000000000000104083408558608425664715468883514404296875"} 0
bug_report_not_rendered_bucket{le="0.01000000000000000020816681711721685132943093776702880859375"} 1
bug_report_not_rendered_bucket{le="0.025000000000000001387778780781445675529539585113525390625"} 1
bug_report_not_rendered_bucket{le="0.05000000000000000277555756156289135105907917022705078125"} 1
bug_report_not_rendered_bucket{le="0.07499999999999999722444243843710864894092082977294921875"} 1
bug_report_not_rendered_bucket{le="0.1000000000000000055511151231257827021181583404541015625"} 1
bug_report_not_rendered_bucket{le="0.25"} 1
bug_report_not_rendered_bucket{le="0.5"} 1
bug_report_not_rendered_bucket{le="0.75"} 1
bug_report_not_rendered_bucket{le="1"} 1
bug_report_not_rendered_bucket{le="2.5"} 1
bug_report_not_rendered_bucket{le="5"} 1
bug_report_not_rendered_bucket{le="7.5"} 1
bug_report_not_rendered_bucket{le="10"} 1
bug_report_not_rendered_bucket{le="+Inf"} 1
bug_report_not_rendered_count 1
bug_report_not_rendered_sum 0.01000000000000000020816681711721685132943093776702880859375
# HELP php_info Information about the PHP environment.
# TYPE php_info gauge
php_info{version="7.4.9"} 1
```

observe(1)
```
# HELP bug_report_not_rendered Bug report for histograms not rendering
# TYPE bug_report_not_rendered histogram
bug_report_not_rendered_bucket{le="0.005000000000000000104083408558608425664715468883514404296875"} 0
bug_report_not_rendered_bucket{le="0.01000000000000000020816681711721685132943093776702880859375"} 0
bug_report_not_rendered_bucket{le="0.025000000000000001387778780781445675529539585113525390625"} 0
bug_report_not_rendered_bucket{le="0.05000000000000000277555756156289135105907917022705078125"} 0
bug_report_not_rendered_bucket{le="0.07499999999999999722444243843710864894092082977294921875"} 0
bug_report_not_rendered_bucket{le="0.1000000000000000055511151231257827021181583404541015625"} 0
bug_report_not_rendered_bucket{le="0.25"} 0
bug_report_not_rendered_bucket{le="0.5"} 0
bug_report_not_rendered_bucket{le="0.75"} 0
bug_report_not_rendered_bucket{le="1"} 1
bug_report_not_rendered_bucket{le="2.5"} 1
bug_report_not_rendered_bucket{le="5"} 1
bug_report_not_rendered_bucket{le="7.5"} 1
bug_report_not_rendered_bucket{le="10"} 1
bug_report_not_rendered_bucket{le="+Inf"} 1
bug_report_not_rendered_count 1
bug_report_not_rendered_sum 1
# HELP php_info Information about the PHP environment.
# TYPE php_info gauge
php_info{version="7.4.9"} 1
```

observe(1) and then observe(0.01)
```
# HELP bug_report_not_rendered Bug report for histograms not rendering
# TYPE bug_report_not_rendered histogram
bug_report_not_rendered_bucket{le="0.005000000000000000104083408558608425664715468883514404296875"} 0
bug_report_not_rendered_bucket{le="0.01000000000000000020816681711721685132943093776702880859375"} 1
bug_report_not_rendered_bucket{le="0.025000000000000001387778780781445675529539585113525390625"} 1
bug_report_not_rendered_bucket{le="0.05000000000000000277555756156289135105907917022705078125"} 1
bug_report_not_rendered_bucket{le="0.07499999999999999722444243843710864894092082977294921875"} 1
bug_report_not_rendered_bucket{le="0.1000000000000000055511151231257827021181583404541015625"} 1
bug_report_not_rendered_bucket{le="0.25"} 1
bug_report_not_rendered_bucket{le="0.5"} 1
bug_report_not_rendered_bucket{le="0.75"} 1
bug_report_not_rendered_bucket{le="1"} 2
bug_report_not_rendered_bucket{le="2.5"} 2
bug_report_not_rendered_bucket{le="5"} 2
bug_report_not_rendered_bucket{le="7.5"} 2
bug_report_not_rendered_bucket{le="10"} 2
bug_report_not_rendered_bucket{le="+Inf"} 2
bug_report_not_rendered_count 2
bug_report_not_rendered_sum 1.0100000000000000088817841970012523233890533447265625
# HELP php_info Information about the PHP environment.
# TYPE php_info gauge
php_info{version="7.4.9"} 1
```

> So i really thing the problem is not bound to redis itself.
I think this depends on how you look at it. For us, the problem is with Redis Storage because of the float comparison. The precision being returned by Redis is different from what we're passing in (17 vs 60).

**Comment by LKaemmerling** [comment] 2020-11-11 05:47
I guess i found something. What is the output when you run `php -i | grep 'precision'` ?  

My first assumption is that it isn't the default (default is 14):
```
➜ php -i | grep 'precision'
precision => 14 => 14
```

So basically the only "fix" i can imagine would be hardlimiting the buckets to something like "max 3/4 digits after the dot".

**Comment by LKaemmerling** [comment] 2020-11-11 05:49
Okay, my assumption was correct. I guess you have set `precision=60`, because with that precision i see the same label values as you see :)
```
bug_report_not_rendered_bucket{le="0.005000000000000000104083408558608425664715468883514404296875"} 1
bug_report_not_rendered_bucket{le="0.01000000000000000020816681711721685132943093776702880859375"} 1
bug_report_not_rendered_bucket{le="0.025000000000000001387778780781445675529539585113525390625"} 1
bug_report_not_rendered_bucket{le="0.05000000000000000277555756156289135105907917022705078125"} 1
bug_report_not_rendered_bucket{le="0.07499999999999999722444243843710864894092082977294921875"} 1
bug_report_not_rendered_bucket{le="0.1000000000000000055511151231257827021181583404541015625"} 1
```

So the only "fix" i would see, would be limit the float number to something like max. 16 digits after the dot. I will prepare a small MR with that fix and then i would ask you to test it out :)

**Comment by LKaemmerling** [comment] 2020-11-11 06:20
Okay limiting the number is not that easy, because PHP just ignores it, i would need to cast it to a string (otherwise PHP will always store the 60 numbers after the dot)....

**Comment by LKaemmerling** [comment] 2020-11-11 06:54
So i talked a bit with a few other PHP devs and i think this is not fixable, because it is a "problem" that you configured.
```
<?php
ini_set('precision',60);
var_dump(0.05); // 0.05000000000000000277555756156289135105907917022705078125
var_dump(round(0.05, 20)); // 0.05000000000000000277555756156289135105907917022705078125; expected would be 0.0500000000000000000 ==> 0.05
var_dump(number_format(0.05, 20)); // "0.05000000000000000278"
var_dump(number_format(round(0.05, 20), 20)); // "0.05000000000000000278"; Expected would be "0.0500000000000000000"
```

By setting the precision to 60 PHP basically "ignores" every other "precision" given, like on the round command.

**Comment by itongTripleLift** [comment] 2020-11-11 14:45
@LKaemmerling yup that was it. We didn't realize that the default precision of 14 was being overwritten 🤦 . We're using the default precision now and the metrics are working as expected.

**Comment by LKaemmerling** [comment] 2020-11-12 05:48
Great :) I will close this issue then.

**Closed by LKaemmerling** 2020-11-12 05:48 UTC
